import React, { useState } from 'react';
import { 
  X, 
  Copy, 
  Check, 
  Send, 
  CheckCircle2,
  Calendar,
  Clock,
  Repeat,
  Video,
  MapPin
} from 'lucide-react';
import { Client, TherapistProfile, ClientInvitation, RecurrenceCadence, SessionLocation } from '../types';
import { invitationsApi, inviteLink } from '../api';
import { InviteRelationship, InvitePayload } from './InviteRelationship';
import { INITIAL_THERAPIST_PROFILE } from '../data/therapistData';
import { DAYS_OF_WEEK, TIME_SLOTS, DURATION_OPTIONS, CURRENT_WEEK_DATES } from '../data/calendarUtils';

interface InviteClientModalProps {
  isOpen: boolean;
  onClose: () => void;
  clients?: Client[];
  existingClients?: Client[];
  targetClient?: Client | null;
  preselectedClient?: Client | null;
  therapistProfile?: TherapistProfile;
  onSendInvitation: (invitationData: ClientInvitation) => void;
}

export const InviteClientModal: React.FC<InviteClientModalProps> = ({
  isOpen,
  onClose,
  clients,
  existingClients = [],
  targetClient,
  preselectedClient,
  therapistProfile,
  onSendInvitation,
}) => {
  const allClients = clients || existingClients;
  const currentTarget = preselectedClient !== undefined ? preselectedClient : targetClient;
  const activeProfile = therapistProfile || INITIAL_THERAPIST_PROFILE;

  const [selectedClientId, setSelectedClientId] = useState<string>(
    currentTarget ? currentTarget.id : 'new'
  );
  const [clientName, setClientName] = useState(currentTarget ? currentTarget.name : '');
  const [clientEmail, setClientEmail] = useState(
    currentTarget?.email || (currentTarget ? `${currentTarget.name.toLowerCase().replace(/\s+/g, '.')}@example.com` : '')
  );

  const [welcomeMessage, setWelcomeMessage] = useState(
    `Hi ${currentTarget ? currentTarget.name.split(' ')[0] : 'there'}, I've set up your secure Unclinq space${activeProfile?.practiceName ? ` at ${activeProfile.practiceName}` : ''}. You can log reflections, try between-session exercises, and prepare for our sessions here. — ${activeProfile?.name || 'Your therapist'}`
  );

  const [copiedLink, setCopiedLink] = useState(false);
  const [sentSuccess, setSentSuccess] = useState(false);
  // Real invitation generated by the backend (the code the client redeems).
  const [generatedCode, setGeneratedCode] = useState<string | null>(null);
  const [generatedLink, setGeneratedLink] = useState<string>('');
  const [inviteError, setInviteError] = useState('');
  const [rel, setRel] = useState<InvitePayload>({ relationship_type: 'new', valid: true });
  const [copiedCode, setCopiedCode] = useState(false);

  // Sync state when modal is opened or target client changes
  React.useEffect(() => {
    if (isOpen) {
      if (currentTarget) {
        setSelectedClientId(currentTarget.id);
        setClientName(currentTarget.name);
        setClientEmail(currentTarget.email || `${currentTarget.name.toLowerCase().replace(/\s+/g, '.')}@example.com`);
        setWelcomeMessage(
          `Hi ${currentTarget.name.split(' ')[0]}, I've set up your secure Unclinq space${activeProfile?.practiceName ? ` at ${activeProfile.practiceName}` : ''}. You can log reflections, try between-session exercises, and prepare for our sessions here. — ${activeProfile?.name || 'Your therapist'}`
        );
      } else {
        setSelectedClientId('new');
        setClientName('');
        setClientEmail('');
        setWelcomeMessage(
          `Hi there, I've set up your secure Unclinq space${activeProfile?.practiceName ? ` at ${activeProfile.practiceName}` : ''}. You can log reflections, try between-session exercises, and prepare for our sessions here. — ${activeProfile?.name || 'Your therapist'}`
        );
      }
    }
  }, [isOpen, currentTarget, activeProfile?.practiceName, activeProfile?.name]);

  if (!isOpen) return null;

  // Generate mock secure portal link with practice subdomain
  const practiceSlug = (activeProfile?.practiceName || 'practice').toLowerCase().replace(/[^a-z0-9]/g, '') || 'portal';
  const slug = (clientName || 'client').toLowerCase().replace(/[^a-z0-9]/g, '');
  const portalLink = `https://${practiceSlug}.health/join?token=client-${slug || 'portal'}-${Math.floor(100000 + Math.random() * 900000)}`;

  const handleClientSelectChange = (val: string) => {
    setSelectedClientId(val);
    if (val === 'new') {
      setClientName('');
      setClientEmail('');
      setWelcomeMessage(
        `Hi there, I've set up your secure Unclinq space${activeProfile?.practiceName ? ` at ${activeProfile.practiceName}` : ''}. You can log reflections, try between-session exercises, and prepare for our sessions here. — ${activeProfile?.name || 'Your therapist'}`
      );
    } else {
      const match = allClients.find(c => c.id === val);
      if (match) {
        setClientName(match.name);
        setClientEmail(match.email || `${match.name.toLowerCase().replace(/\s+/g, '.')}@example.com`);
        setWelcomeMessage(
          `Hi ${match.name.split(' ')[0]}, I've set up your secure Unclinq space${activeProfile?.practiceName ? ` at ${activeProfile.practiceName}` : ''}. You can log reflections, try between-session exercises, and prepare for our sessions here. — ${activeProfile?.name || 'Your therapist'}`
        );
      }
    }
  };

  const handleCopyLink = () => {
    navigator.clipboard?.writeText(generatedLink || portalLink);
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2500);
  };

  const handleSendInvite = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!clientName.trim() || !clientEmail.trim()) return;
    if (rel.relationship_type === 'ongoing' && !rel.valid) {
      setInviteError('For an ongoing client, add a summary, current focus, and at least one goal.');
      return;
    }
    setInviteError('');

    // Generate a REAL invitation on the backend — the code the client redeems.
    let realLink = portalLink;
    let code: string | null = null;
    try {
      const res = await invitationsApi.create({
        client_name: clientName.trim(),
        client_email: clientEmail.trim(),
        expires_in_days: 7,
        relationship_type: rel.relationship_type,
        seed_context: rel.seed_context,
      });
      code = res.invitation.code;
      realLink = inviteLink(code);
      setGeneratedCode(code);
      setGeneratedLink(realLink);
    } catch (err: any) {
      setInviteError(err?.data?.error || err?.message || 'Could not create the invitation. Please try again.');
      return;
    }

    onSendInvitation({
      id: `inv-${Date.now()}`,
      clientId: selectedClientId !== 'new' ? selectedClientId : undefined,
      clientName: clientName.trim(),
      clientEmail: clientEmail.trim(),
      clientPhone: currentTarget?.phone,
      preferredPronouns: currentTarget?.preferredPronouns,
      portalLink: realLink,
      invitationCode: code,
      status: 'pending',
      sentDate: 'Today',
      forms: ['Initial Intake & Goals Questionnaire', 'HIPAA Informed Consent & Telehealth Agreement', 'Longitudinal Check-in Companion (Emora)'],
      customWelcomeNote: welcomeMessage,
    } as ClientInvitation);

    setSentSuccess(true); // stays open so the therapist can copy the code
  };

  const handleCopyCode = () => {
    if (!generatedCode) return;
    navigator.clipboard?.writeText(generatedCode);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2500);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 overflow-y-auto">
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-[#10151F]/30 backdrop-blur-sm transition-opacity"
        onClick={onClose}
      />

      {/* Modal Card */}
      <div className="relative w-full max-w-2xl bg-white rounded-2xl border border-[#ECEFF3] shadow-[0_20px_60px_rgba(16,21,31,0.18)] overflow-hidden animate-in fade-in zoom-in-95 duration-150 my-8">
        
        {/* Header */}
        <div className="p-6 sm:p-7 border-b border-[#F2F5F8] bg-white flex items-center justify-between gap-4">
          <div className="flex items-center space-x-3.5">
            {activeProfile?.logoUrl ? (
              <img
                src={activeProfile.logoUrl}
                alt={activeProfile.practiceName || 'Practice'}
                referrerPolicy="no-referrer"
                className="w-12 h-12 rounded-2xl object-cover border border-[#ECEFF3] shrink-0"
              />
            ) : (
              <div className="w-12 h-12 rounded-2xl bg-[#F1FAF9] text-[#0F766E] flex items-center justify-center font-serif font-semibold text-lg shrink-0">
                {activeProfile?.practiceName ? activeProfile.practiceName[0] : 'P'}
              </div>
            )}
            <div>
              <div className="flex items-center space-x-2">
                <span className="u-eyebrow">
                  Client Portal Invitation
                </span>
                <span className="text-xs text-[#9AA4B2]">
                  {activeProfile.practiceName}
                </span>
              </div>
              <h2 className="text-xl sm:text-2xl font-serif font-semibold text-[#10151F] mt-0.5">
                Invite Client to {activeProfile?.practiceName || 'Client Portal'}
              </h2>
              <p className="text-xs sm:text-sm text-[#6B7686]">
                Connect your client to between-session journaling, actions, and intake questionnaires
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-lg text-[#9AA4B2] hover:text-[#10151F] hover:bg-[#F1F5F9] transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form Body */}
        <form onSubmit={handleSendInvite} className="p-6 sm:p-8 space-y-6 max-h-[72vh] overflow-y-auto">
          
          {/* Target Client Selector */}
          <div>
            <label className="block text-[13px] font-medium text-[#3A4453] mb-1.5">
              Invitation Recipient
            </label>
            <select
              value={selectedClientId}
              onChange={(e) => handleClientSelectChange(e.target.value)}
              className="w-full bg-[#F7F9FB] border border-[#ECEFF3] rounded-lg px-3.5 py-2.5 text-sm text-[#10151F] focus:outline-none focus:border-[#0D9488] focus:bg-white transition-colors cursor-pointer"
            >
              <option value="new">+ Invite a new client to practice</option>
              <optgroup label="Existing Caseload">
                {existingClients.map(c => (
                  <option key={c.id} value={c.id}>
                    {c.name} {c.portalStatus === 'invited' ? '(Invited)' : ''}
                  </option>
                ))}
              </optgroup>
            </select>
          </div>

          {/* Client Details Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-[13px] font-medium text-[#3A4453] mb-1.5">
                Client Full Name *
              </label>
              <input
                type="text"
                required
                value={clientName}
                onChange={(e) => setClientName(e.target.value)}
                placeholder="e.g. Maya Lin"
                className="w-full bg-[#F7F9FB] border border-[#ECEFF3] rounded-lg px-3.5 py-2.5 text-sm text-[#10151F] placeholder-[#9AA4B2] focus:outline-none focus:border-[#0D9488] focus:bg-white transition-colors"
              />
            </div>

            <div>
              <label className="block text-[13px] font-medium text-[#3A4453] mb-1.5">
                Client Email *
              </label>
              <input
                type="email"
                required
                value={clientEmail}
                onChange={(e) => setClientEmail(e.target.value)}
                placeholder="client@example.com"
                className="w-full bg-[#F7F9FB] border border-[#ECEFF3] rounded-lg px-3.5 py-2.5 text-sm text-[#10151F] placeholder-[#9AA4B2] focus:outline-none focus:border-[#0D9488] focus:bg-white transition-colors"
              />
            </div>
          </div>

          {/* New vs Ongoing client — ongoing requires a little history (seeded on redeem) */}
          <InviteRelationship onChange={setRel} />


          {/* Welcome Message */}
          <div className="space-y-1.5">
            <label className="block text-[13px] font-medium text-[#3A4453]">
              Personalized Welcome Note
            </label>
            <textarea
              rows={3}
              value={welcomeMessage}
              onChange={(e) => setWelcomeMessage(e.target.value)}
              className="w-full bg-[#F7F9FB] border border-[#ECEFF3] rounded-lg px-3.5 py-2.5 text-xs sm:text-sm text-[#10151F] placeholder-[#9AA4B2] focus:outline-none focus:border-[#0D9488] focus:bg-white transition-colors leading-relaxed"
            />
          </div>

          {/* Portal Link Box & One-Click Copy */}
          <div className="p-4 rounded-xl bg-[#F7F9FB] border border-[#ECEFF3] space-y-2">
            <div className="flex items-center justify-between text-xs">
              <span className="u-eyebrow">
                Direct Portal Registration Link
              </span>
              {copiedLink && (
                <span className="text-[#0F766E] font-medium flex items-center gap-1">
                  <Check className="w-3.5 h-3.5" />
                  Link Copied!
                </span>
              )}
            </div>
            <div className="flex items-center space-x-2">
              <input
                type="text"
                readOnly
                value={generatedLink || portalLink}
                className="flex-1 px-3.5 py-2.5 bg-white border border-[#ECEFF3] rounded-lg text-xs font-mono text-[#3A4453] select-all focus:outline-none"
              />
              <button
                type="button"
                onClick={handleCopyLink}
                className="u-btn-ghost text-xs shrink-0"
              >
                <Copy className="w-3.5 h-3.5 text-[#6B7686]" />
                <span>{copiedLink ? 'Copied' : 'Copy'}</span>
              </button>
            </div>
            <p className="text-[11px] text-[#6B7686]">
              Clients can open this link on mobile or desktop to accept the invitation and begin their intake.
            </p>
          </div>

          {inviteError && (
            <div className="p-3 rounded-lg bg-[#FDF2F2] border border-[#F5C6C6] text-[#B0332F] text-xs sm:text-sm">{inviteError}</div>
          )}

          {/* Success — show the REAL invitation code the client redeems */}
          {sentSuccess && generatedCode && (
            <div className="p-5 rounded-xl bg-[#F1FAF9] border border-[#CCE9E6] space-y-3 animate-in fade-in duration-150">
              <div className="flex items-center gap-2 text-[#0F766E] text-sm font-medium">
                <CheckCircle2 className="w-5 h-5 text-[#0D9488] shrink-0" />
                <span>Invitation ready for {clientName}. Share the code or link below.</span>
              </div>
              <div className="flex items-center justify-between gap-3 bg-white border border-[#CCE9E6] rounded-lg px-4 py-3">
                <div>
                  <p className="u-eyebrow">Invitation code</p>
                  <p className="text-2xl font-mono font-semibold tracking-[0.25em] text-[#10151F] mt-0.5">{generatedCode}</p>
                </div>
                <button type="button" onClick={handleCopyCode} className="u-btn-ghost text-xs shrink-0">
                  {copiedCode ? <Check className="w-3.5 h-3.5 text-[#0F766E]" /> : <Copy className="w-3.5 h-3.5 text-[#6B7686]" />}
                  <span>{copiedCode ? 'Copied' : 'Copy code'}</span>
                </button>
              </div>
              <p className="text-[11px] text-[#6B7686]">
                {clientName} creates their own account with this code — expires in 7 days. You’ll see them as “Connected” once they finish onboarding.
              </p>
            </div>
          )}

          {/* Action Footer */}
          <div className="pt-2 border-t border-[#F2F5F8] flex flex-col-reverse sm:flex-row items-center justify-end gap-3">
            <button
              type="button"
              onClick={onClose}
              className="u-btn-ghost w-full sm:w-auto justify-center"
            >
              Cancel
            </button>

            <button
              type="submit"
              disabled={sentSuccess || (rel.relationship_type === 'ongoing' && !rel.valid)}
              className="u-btn-primary w-full sm:w-auto justify-center disabled:opacity-50"
            >
              <Send className="w-4 h-4 text-[#2DD4BF]" />
              <span>{sentSuccess ? 'Sending...' : 'Send Invitation via Email'}</span>
            </button>
          </div>

        </form>

      </div>
    </div>
  );
};
